-- Categories
INSERT INTO categories (id, name) VALUES
                                      (1, 'Beer'),
                                      (2, 'Beverage'),
                                      (3, 'Burrito'),
                                      (4, 'Mulita'),
                                      (5, 'Nopal asado'),
                                      (6, 'Quesadilla'),
                                      (7, 'Side'),
                                      (8, 'Taco'),
                                      (9, 'Torta');

-- Menu Items
INSERT INTO menu_items (id, name, price, category_id) VALUES
                                                          (1,  'Taco pollo',                2.95, 8),
                                                          (2,  'Taco frijoles',             2.95, 8),
                                                          (3,  'Taco asada',                2.95, 8),
                                                          (4,  'Taco nopal',                2.95, 8),
                                                          (5,  'Taco adobada',              2.95, 8),
                                                          (6,  'Taco chukis',               3.35, 8),
                                                          (7,  'Mulita pollo',              3.75, 4),
                                                          (8,  'Mulita frijoles',           3.75, 4),
                                                          (9,  'Mulita asada',              3.75, 4),
                                                          (10, 'Mulita nopal',              3.75, 4),
                                                          (11, 'Mulita adobada',            3.75, 4),
                                                          (12, 'Burrito frijoles',          4.80, 3),
                                                          (13, 'Burrito asada',             4.80, 3),
                                                          (14, 'Burrito nopal',             4.80, 3),
                                                          (15, 'Burrito adobada',           4.80, 3),
                                                          (16, 'Burrito pollo',             4.80, 3),
                                                          (17, 'Quesadilla asada',          5.90, 6),
                                                          (18, 'Quesadilla nopal',          5.90, 6),
                                                          (19, 'Quesadilla pollo',          5.90, 6),
                                                          (20, 'Quesadilla frijoles',       5.90, 6),
                                                          (21, 'Quesadilla adobada',        5.90, 6),
                                                          (22, 'Quesadilla plain cheese',   3.50, 6),
                                                          (23, 'Nopal asado frijoles',      9.25, 5),
                                                          (24, 'Nopal asado asada',         9.25, 5),
                                                          (25, 'Nopal asado adobada',       9.25, 5),
                                                          (26, 'Nopal asado pollo',         9.25, 5),
                                                          (27, 'Torta nopales',             9.25, 9),
                                                          (28, 'Torta adobada',             9.25, 9),
                                                          (29, 'Torta pollo',               9.25, 9),
                                                          (30, 'Torta frijoles',            9.25, 9),
                                                          (31, 'Torta asada',               9.25, 9),
                                                          (32, 'Bottle soda',               3.35, 2),
                                                          (33, 'Horchata',                  3.35, 2),
                                                          (34, 'Jamaica',                   3.35, 2),
                                                          (35, 'Can soda',                  2.25, 2),
                                                          (36, 'Guacamole sauce',           0.23, 7),
                                                          (37, 'Spicy sauce',               0.23, 7),
                                                          (38, 'Piece of lime',             0.23, 7),
                                                          (39, 'Modelo 16oz',               6.00, 1),
                                                          (40, 'Pacifico 16oz',             6.00, 1),
                                                          (41, 'Tecate 16oz',               5.00, 1);
